---
- name: Create RG
  hosts: localhost
  connection: local
  collections:
  - azure.azcollection
  
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: rg_test
      location: uksouth
